### ISSUE TITLE
bug: gif has black background

### ISSUE THREAD

**Issue by LuckyTurtleDev** [sot-tech/LottieConverter#2]
If I convert a animated lottie file to a gif, I get a gif with a black background.
But if I does convert this to an png it is still transparent.

I have test it with the telegram duck tickerpack: https://t.me/addstickers/UtyaDuck

**Comment by sot-tech** [comment]
Hello.

For now, it broken by design (see option parameter in README).
Unfortunately, I did not fully understand how gif.h works with Alpha, it quite creepy (see example below). Perhaps a little later I will do further experiments.

![out](https://user-images.githubusercontent.com/41361221/140642553-4f037fe2-ccad-4255-b5f7-6f8270fadbe4.gif)

P.S. GIF does not support native alpha channel and setting one color as transparent is rudimentary dirty hack, IMAO.

**Comment by LuckyTurtleDev** [comment]
Hi, have found a very new alternative program, with does support transparent and does also use rlottie. 
https://github.com/msrd0/rlottie-rs/commit/cb90e5206b170e91d1a6d720051c1242edcf82ce
You may would like to take a look at the implementation.
I have start using this now, but thanks for your efforts.

**Comment by sot-tech** [comment]
Happy for you!

Maybe rust is better solution in your case. 
There is no so many good and lightweight GIF encoders in c/c++.
