### ISSUE TITLE
Increase define li_MAX_DIMENSION 4000

### ISSUE THREAD

**Issue by 4815162342lost** [sot-tech/LottieConverter#4]
Hello, Thanks a lot for your program. It works!

But i suggest to increase li_MAX_DIMENSION up to 8192.

In some cases 4000 not enough. For example, i want extract frame and print to wall (print a picture in real life).

Is it possible?
https://github.com/sot-tech/LottieConverter/blob/190dc6629e18c03a357b8c3c05844b2394ac3593/lottie_export.h#L38

**Comment by sot-tech** [comment]
Hello.
I will try increase limit to 16384 soon and check memory consumption.

Such small utility should not be greedy in memory i think, so 16384 will enough for regular usage.

But you might change this value by yourself and recompile utility, or maybe you need only compiled executable?

**Comment by sot-tech** [comment]
I won't create new release because it is not such big change.

If you need precompiled modules, see attachments:

[lottieconverter-0.2-alpine-edge-musl-amd64-3e38ee5.tar.gz](https://github.com/sot-tech/LottieConverter/files/8577643/lottieconverter-0.2-alpine-edge-musl-amd64-3e38ee5.tar.gz)
[lottieconverter-0.2-ubuntu-20.04-amd64-3e38ee5.tar.gz](https://github.com/sot-tech/LottieConverter/files/8577644/lottieconverter-0.2-ubuntu-20.04-amd64-3e38ee5.tar.gz)
